// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/store_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pb "github.com/AkikoAkaki/async-task-platform/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockJobStore is a mock of JobStore interface.
type MockJobStore struct {
	ctrl     *gomock.Controller
	recorder *MockJobStoreMockRecorder
	isgomock struct{}
}

// MockJobStoreMockRecorder is the mock recorder for MockJobStore.
type MockJobStoreMockRecorder struct {
	mock *MockJobStore
}

// NewMockJobStore creates a new mock instance.
func NewMockJobStore(ctrl *gomock.Controller) *MockJobStore {
	mock := &MockJobStore{ctrl: ctrl}
	mock.recorder = &MockJobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobStore) EXPECT() *MockJobStoreMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockJobStore) Ack(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockJobStoreMockRecorder) Ack(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockJobStore)(nil).Ack), ctx, id)
}

// Add mocks base method.
func (m *MockJobStore) Add(ctx context.Context, task *pb.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockJobStoreMockRecorder) Add(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockJobStore)(nil).Add), ctx, task)
}

// CheckAndMoveExpired mocks base method.
func (m *MockJobStore) CheckAndMoveExpired(ctx context.Context, visibilityTimeout int64, maxRetries int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndMoveExpired", ctx, visibilityTimeout, maxRetries)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAndMoveExpired indicates an expected call of CheckAndMoveExpired.
func (mr *MockJobStoreMockRecorder) CheckAndMoveExpired(ctx, visibilityTimeout, maxRetries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndMoveExpired", reflect.TypeOf((*MockJobStore)(nil).CheckAndMoveExpired), ctx, visibilityTimeout, maxRetries)
}

// FetchAndHold mocks base method.
func (m *MockJobStore) FetchAndHold(ctx context.Context, topic string, limit int64) ([]*pb.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndHold", ctx, topic, limit)
	ret0, _ := ret[0].([]*pb.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAndHold indicates an expected call of FetchAndHold.
func (mr *MockJobStoreMockRecorder) FetchAndHold(ctx, topic, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndHold", reflect.TypeOf((*MockJobStore)(nil).FetchAndHold), ctx, topic, limit)
}

// Nack mocks base method.
func (m *MockJobStore) Nack(ctx context.Context, task *pb.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nack", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nack indicates an expected call of Nack.
func (mr *MockJobStoreMockRecorder) Nack(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nack", reflect.TypeOf((*MockJobStore)(nil).Nack), ctx, task)
}

// Remove mocks base method.
func (m *MockJobStore) Remove(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockJobStoreMockRecorder) Remove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockJobStore)(nil).Remove), ctx, id)
}
